version: 0.0
os: linux
files:
  - source: build/libs/VulnerableApp-1.0.0.jar
    destination: /opt/vulnerableapp/

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 100
      runas: root
  AfterInstall:
    - location: scripts/install_server.sh
      timeout: 100
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 100
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 100
      runas: root