version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - apt-get update
      - apt-get install -y gradle zip

  pre_build:
    commands:
      - echo "Pre-build started"
      - chmod +x gradlew
      - ./gradlew clean

  build:
    commands:
      - echo "Build started"
      - ./gradlew build

  post_build:
    commands:
      - echo "Build Completed!!"
      - echo "Creating ZIP file of build artifacts"
      - mkdir -p build-artifacts
      - cp build/libs/*.jar build-artifacts/
      - zip -r build-artifacts.zip build-artifacts/
      - echo "ZIP file created"

artifacts:
  files:
    - build-artifacts.zip
  discard-paths: yes
