version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - apt-get update
      - apt-get install -y gradle
  pre_build:
    commands:
      - echo "Pre-build started"
      - chmod +x gradlew
      - ./gradlew clean
  build:
    commands:
      - echo "Build started"
      - ./gradlew build
      - chmod +x scripts/*.sh

artifacts:
  files:
    - '**/*'