version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - apt-get update
      - apt-get install gradle -y
  pre_build:
    commands:
      - chmod +x gradlew
      - ./gradlew clean
  build:
    commands:
      - ./gradlew build
  post_build:
    commands:
      - echo "Build Completed!!"
artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes
  packaging: zip 