version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - apt-get update
      - apt-get install gradle -y

  build:
    commands:
      - chmod +x gradlew
      - ./gradlew build
 
artifacts:
  files:
    - '**/*''