version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - apt-get update
      - apt-get install -y gradle
      - chmod +x scripts/start_server.sh
      - chmod +x scripts/stop_server.sh
      - chmod +x scripts/install_dependencies.sh
      - chmod +x scripts/install_server.sh
  pre_build:
    commands:
      - echo "Pre-build started"
      - chmod +x gradlew
      - ./gradlew clean
  build:
    commands:
      - echo "Build started"
      - ./gradlew build
      - chmod +x scripts/*.sh

artifacts:
  files:
    - '**/*'